package:
  name: ccpi-dvc
  version: 21.1.0

build:
  preserve_egg_dir: False
  number: 1

requirements:
  build:
    - setuptools
    - boost >=1.65
    - boost-cpp >=1.65
    - cmake >=3.9

  run:
    - boost >=1.65
	
about:
  home: http://www.ccpi.ac.uk
  license:  BSD license
  summary: 'CCPi Core Imaging Library DVC Toolbox'
