package:
  name: ccpi-dvc
  version: 21.1.0

build:
  preserve_egg_dir: False
  number: 1

requirements:
  build:
    - openmp # [osx]

  run:
    - openmp # [osx]
	
about:
  home: http://www.ccpi.ac.uk
  license:  BSD license
  summary: 'CCPi Core Imaging Library DVC Toolbox'
