package:
  name: ccpi-dvc
  version: 21.0.0

build:
  preserve_egg_dir: False
  

  entry_points:
    - idvc = ccpi.dvc.apps.dvc_interface:main
  number: 3
  
requirements:
  build:
    - python 
    - openmp # [osx]
    - cmake
    
 
  run:
    - python
    - numpy
    - ccpi-viewer >=21.0
    - natsort
    - docopt
    - matplotlib
    - openmp # [osx]
    

    

about:
  home: http://www.ccpi.ac.uk
  license:  Apache v.2.0 license
  summary: 'CCPi Digital Volume Correlation GUI'
