package:
  name: ccpi-dvc-app-prototype1
  version: {{ environ['CIL_VERSION'] }}


build:
  preserve_egg_dir: False
  script_env:
    - CIL_VERSION

  entry_points:
    - DVC_Interface = ccpi.dvc.apps.DVC_Interface:main

  number: 7
  
requirements:
  build:
    - python 
    - setuptools
    - cython
    - numpy
 
  run:
    - python
    - numpy
    - ccpi-viewer
#    - ccpi-dvc
    - natsort
    - docopt
    - tqdm
    

about:
  home: http://www.ccpi.ac.uk
  license:  Apache v.2.0 license
  summary: 'CCPi Core Imaging Library (Viewer)'
