package:
  name: ccpi-dvc
  version: 20.07.2
# conda build ... -c file://my_local_channel --override-channels

build:
  preserve_egg_dir: False
  

  entry_points:
    - DVC_Interface = ccpi.dvc.apps.dvc_interface:main
  number: 0
  
requirements:
  build:
    - python 
    - setuptools
    
 
  run:
    - python
    - numpy
    - ccpi-viewer ==20.07.2
    - natsort
    - docopt
    - tqdm
    

about:
  home: http://www.ccpi.ac.uk
  license:  Apache v.2.0 license
  summary: 'CCPi Digital Volume Correlation GUI'
