package:
  name: ccpi-dvc-app-prototype1
  version: 20.06.8
# conda build ... -c file://my_local_channel --override-channels

build:
  preserve_egg_dir: False
  

  entry_points:
    - DVC_Interface = ccpi.dvc.apps.dvc_interface:main
    - dvc_runner = ccpi.dvc.apps.dvc_runner:main

  number: 2
  
requirements:
  build:
    - python 
    - setuptools
    - cython
    - numpy
 
  run:
    - python
    - numpy
    - ccpi-viewer
    - natsort
    - docopt
    - tqdm
    

about:
  home: http://www.ccpi.ac.uk
  license:  Apache v.2.0 license
  summary: 'CCPi Core Imaging Library (Viewer)'
